### ISSUE TITLE
Bones not affected by different curve types

### ISSUE THREAD

**Issue by loodakrawa** [thorthur/gdx-spriter#2]
Fix: 
https://github.com/loodakrawa/SpriterDotNet/commit/25d252b5f6789d7606d0a2bd5b729383da43619b

**Comment by arthurtemple** [comment]
Many thanks!
Fixed with thorthur/gdx-spriter@24c8933.

By the way, I had already switched to adjusted time in the interpolation for `VariableValue`s but I would not be unable to tell you why, incidental change maybe.
